language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'grunt-sp_module' ]; then cd .. && eval "mv $currentfolder grunt-sp_module" && cd grunt-sp_module; fi

